AlexaSoft_ASP.NET/Models/Compra.cs
using System;
using System.Collections.Generic;


namespace AlexaSoft_ASP.NET.Models
{
    public partial class Compra
    {
        public int IdCompra { get; set; }

        public int? IdProveedor { get; set; }

   
        public int Precio { get; set; }

    
        public DateTime Fecha { get; set; }

       
        public int Subtotal { get; set; }

        public string? MotivoAnular { get; set; }

        public virtual ICollection<Detallesproductosxcompra> Detallesproductosxcompras { get; set; } = new List<Detallesproductosxcompra>();

        public virtual Proveedore? IdProveedorNavigation { get; set; }
    }
}

AlexaSoft_ASP.NET/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlexaSoft_ASP.NET.Models;
using System.Data;
using AlexaSoft_ASP.NET.Utilities;

namespace AlexaSoft_ASP.NET.Controllers
{
    public class ComprasController : Controller
    {
        private readonly AlexasoftContext _context;

        public ComprasController(AlexasoftContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            var alexasoftContext = _context.Compras.Include(c => c.IdProveedorNavigation);
            return View(await alexasoftContext.ToListAsync());
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.IdProveedorNavigation)
                .FirstOrDefaultAsync(m => m.IdCompra == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()

        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "Nombre");
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "Nombre");

            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCompra,IdProveedor,Precio,Fecha,Subtotal,MotivoAnular")] Compra compra, int idProducto, int Unidades, int idDetalles)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (ModelState.IsValid)
            {
                _context.Add(compra);
                int compraSaved = await _context.SaveChangesAsync();
                if (Unidades == null)
                {
                    ModelState.AddModelError("Ingrese una cantidad", "Ingrese una cantidad.");
                    ;
                    return View(compra);
                }

                if (compraSaved > 0)
                {
                    int i = Guid.NewGuid().GetHashCode();


                    Detallesproductosxcompra detallesproductosxcompra = new Detallesproductosxcompra
                    {
                        IdDetalleProductoXcompra = i,
                        IdCompra = compra.IdCompra,
                        IdProducto = idProducto,
                        Unidades = Unidades
                    };

                    _context.Detallesproductosxcompras.Add(detallesproductosxcompra);
                    await _context.SaveChangesAsync();
                }
                var producto = await _context.Productos.FindAsync(idProducto);
                if (producto != null)
                {
                    producto.Unidades += Unidades;
                    _context.Productos.Update(producto);
                    await _context.SaveChangesAsync();
                }


                return RedirectToAction(nameof(Index));

            }
            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "IdProveedor", compra.IdProveedor);



            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "IdProveedor", compra.IdProveedor);
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCompra,IdProveedor,Precio,Fecha,Subtotal,MotivoAnular")] Compra compra)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id != compra.IdCompra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (!string.IsNullOrEmpty(compra.MotivoAnular))
                    {
                        var detallesCompra = await _context.Detallesproductosxcompras.Where(d => d.IdCompra == compra.IdCompra).ToListAsync();
                        if (detallesCompra != null)
                        {
                            // Restar las unidades de los productos correspondientes
                            foreach (var detalle in detallesCompra)
                            {
                                var producto = await _context.Productos.FindAsync(detalle.IdProducto);
                                if (producto != null)
                                {
                                    producto.Unidades -= detalle.Unidades;
                                    _context.Update(producto);
                                }
                            }
                        }
                    }
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.IdCompra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdProveedor"] = new SelectList(_context.Proveedores, "IdProveedor", "IdProveedor", compra.IdProveedor);
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.IdProveedorNavigation)
                .FirstOrDefaultAsync(m => m.IdCompra == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Compras"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (_context.Compras == null)
            {
                return Problem("Entity set 'AlexasoftContext.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
          return (_context.Compras?.Any(e => e.IdCompra == id)).GetValueOrDefault();
        }
    }
}

AlexaSoft_ASP.NET/Views/Compras/Create.cshtml
@model AlexaSoft_ASP.NET.Models.Compra

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Crear Compra</h1>
        </div>
        <div class="col-3">
        </div>
    </div> <!--Fin Row-->
</div>
<hr />

        <div class="container bordeVino px-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdProveedor" class="control-label"></label>
                <select asp-for="IdProveedor" class ="form-control" asp-items="ViewBag.IdProveedor"></select>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotivoAnular" class="control-label"></label>
                <input asp-for="MotivoAnular" class="form-control" />
                <span asp-validation-for="MotivoAnular" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label id="IdProductos" class="control-label"></label>
                <select id="idProducto" name="idProducto" class="form-control" asp-items="ViewBag.IdProducto"></select>
            </div>
        <div class="form-group">
            <label id="Unidades" class="control-label">Unidades</label>
            <input id="Unidades" name="Unidades" class="form-control" type="number" placeholder="Ingrese solo numero" required pattern="[0-9]+" title="Ingrese solo números" />
            <span class="text-danger" id="unidadesError"></span>
        </div>

            <br />
            <div class="mb-3 row">
                <div class="text-center">
                    <input type="submit" value="Crear" class="btn btn-lg fondoVino text-light">
                </div>
            </div>
       </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}



<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

AlexaSoft_ASP.NET/Views/Compras/Delete.cshtml
@model AlexaSoft_ASP.NET.Models.Compra

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h1 class="text-center">Compras</h1>
        </div>
        <div class="col-3"></div>
    </div>
</div>
<h3>Estas seguro de Eliminar este registro?</h3>

<div class="container bordeVino px-4">
    <h4>Eliminar compras</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotivoAnular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotivoAnular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProveedorNavigation.IdProveedor)
        </dd>
    </dl>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdCompra" />
        <a class="btn btn-secondary" asp-action="Index">Cancelar</a> |
        <input class="btn btn-danger" type="submit" value="Delete" />
    </form>
</div>

AlexaSoft_ASP.NET/Views/Compras/Details.cshtml
@model AlexaSoft_ASP.NET.Models.Compra

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Detalle Compra</h1>
        </div>
        <div class="col-3">
        </div>
    </div> <!--Fin Row-->
</div>
<hr />

<div class="container bordeVino px-4">
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotivoAnular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotivoAnular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProveedorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProveedorNavigation.IdProveedor)
        </dd>
    </dl>
    <hr />
</div>

<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

AlexaSoft_ASP.NET/Views/Compras/Edit.cshtml
@model AlexaSoft_ASP.NET.Models.Compra

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Editar Compra</h1>
        </div>
        <div class="col-3">
        </div>
    </div> <!--Fin Row-->
</div>
<hr />

<div class="container bordeVino px-4">

        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdCompra" />
            <div class="form-group">
                <label asp-for="IdProveedor" class="control-label"></label>
                <select asp-for="IdProveedor" class="form-control" asp-items="ViewBag.IdProveedor"></select>
                <span asp-validation-for="IdProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotivoAnular" class="control-label"></label>
                <input asp-for="MotivoAnular" class="form-control" />
                <span asp-validation-for="MotivoAnular" class="text-danger"></span>
            </div>
            <br />
            <div class="mb-3 row">
                <div class="text-center">
                    <input type="submit" value="Guardar" class="btn btn-lg fondoVino text-light">
                </div>
            </div>
        </form>
    </div>

<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

AlexaSoft_ASP.NET/Views/Compras/Index.cshtml
@model IEnumerable<AlexaSoft_ASP.NET.Models.Compra>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
          <h1 class="text-center">Compras</h1>
        </div>
        <div class="col-3"></div>
      </div>
    </div> 
    
<p>
    <a asp-action="Create" class="btn btn-lg fondoVino text-light">Crear Compra</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th scope ="col">
                @Html.DisplayNameFor(model => model.Precio)
            </th scope="col">
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th scope="col">
            <th>
                @Html.DisplayNameFor(model => model.Subtotal)
            </th scope="col">
            <th scope="col">
                @Html.DisplayNameFor(model => model.MotivoAnular)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.IdProveedorNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subtotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MotivoAnular)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdProveedorNavigation.Nombre)
            </td>
            <td>
                 @if (string.IsNullOrEmpty(item.MotivoAnular))
                    {
                       <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.IdCompra">Editar</a> 
                        <a class="btn btn-success" asp-action="Details" asp-route-id="@item.IdCompra">Detalle</a>

                    }else
                    {
                        <a class="btn btn-danger delete-btn" asp-action="Delete" asp-route-id="@item.IdCompra">Eliminar</a>
                    }

            </td>
        </tr>
} 
    </tbody>
</table>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function () {
            $('.delete-btn').on('click', function () {
                var compraId = $(this).data('compra-id');
                Swal.fire({
                    title: "Are you sure?",
                    text: "You won't be able to revert this!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Yes, delete it!"
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Realizar la petición de eliminación al controlador
                        $.ajax({
                            url: '@Url.Action("DeleteConfirmed", "Compras")',
                            type: 'POST',
                            data: { id: compraId },
                            success: function (data) {
                                Swal.fire({
                                    title: "Deleted!",
                                    text: "Your file has been deleted.",
                                    icon: "success"
                                }).then(() => {
                                    location.reload(); // Recargar la página
                                });
                            },
                            error: function (error) {
                                console.error(error);
                                Swal.fire({
                                    title: "Error!",
                                    text: "An error occurred while deleting.",
                                    icon: "error"
                                });
                            }
                        });
                    }
                });
            });
        });
    </script>