AlexaSoft_ASP.NET/Models/Servicio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AlexaSoft_ASP.NET.Models;

public partial class Servicio
{
    public int IdServicio { get; set; }
    
    [Required]
    [RegularExpression(@"^[^\d]+$", ErrorMessage = "El campo Nombre no debe contener números.")]
    public string Nombre { get; set; } = null!;
    [Required]
    [RegularExpression(@"^[^\d]+$", ErrorMessage = "El campo Descripcion no debe contener números.")]
    public string Descripcion { get; set; } = null!;

    public int TiempoMinutos { get; set; }

    public string Estado { get; set; } = null!;

    public virtual ICollection<PaquetesServicio> PaquetesServicios { get; set; } = new List<PaquetesServicio>();

    public virtual ICollection<ServiciosProducto> ServiciosProductos { get; set; } = new List<ServiciosProducto>();

}

AlexaSoft_ASP.NET/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlexaSoft_ASP.NET.Models;
using AlexaSoft_ASP.NET.Utilities;

namespace AlexaSoft_ASP.NET.Controllers
{
    public class ServiciosController : Controller
    {
        private readonly AlexasoftContext _context;

        public ServiciosController(AlexasoftContext context)
        {
            _context = context;
        }

        // GET: Servicios
        public async Task<IActionResult> Index()
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            return _context.Servicios != null ? 
                          View(await _context.Servicios.ToListAsync()) :
                          Problem("Entity set 'AlexasoftContext.Servicios'  is null.");
        }

        // GET: Servicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // GET: Servicios/Create
        public IActionResult Create()
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            return View();
        }

        // POST: Servicios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdServicio,Nombre,Descripcion,TiempoMinutos,Estado")] Servicio servicio)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (ModelState.IsValid)
            {
                _context.Add(servicio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(servicio);
        }

        // GET: Servicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio == null)
            {
                return NotFound();
            }
            return View(servicio);
        }

        // POST: Servicios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdServicio,Nombre,Descripcion,TiempoMinutos,Estado")] Servicio servicio)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id != servicio.IdServicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicioExists(servicio.IdServicio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servicio);
        }

        // GET: Servicios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // POST: Servicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!AccesoHelper.TienePermiso(HttpContext, "Gestionar Servicios"))
            {
                return RedirectToAction("Error", "Home");
            }
            if (_context.Servicios == null)
            {
                return Problem("Entity set 'AlexasoftContext.Servicios'  is null.");
            }
            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio != null)
            {
                _context.Servicios.Remove(servicio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> CambiarEstado(int idservicio)
        {

            var rol = await _context.Servicios.FindAsync(idservicio);
            if (rol == null)
            {
                return NotFound();
            }

            rol.Estado = rol.Estado == "Activo" ? "Desactivado" : "Activo";
            await _context.SaveChangesAsync();

            return Ok();
        }

        private bool ServicioExists(int id)
        {
          return (_context.Servicios?.Any(e => e.IdServicio == id)).GetValueOrDefault();
        }
    }
}

AlexaSoft_ASP.NET/Views/Servicios/Create.cshtml
@model AlexaSoft_ASP.NET.Models.Servicio

@{
    ViewData["Title"] = "Create";
}


<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Crear Sericio</h1>
        </div>
        <div class="col-3">
        </div>
    </div> <!--Fin Row-->
</div>
<br>
<br>
    <div class="container bordeVino px-4">
        <br>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoMinutos" class="control-label"></label>
                <input asp-for="TiempoMinutos" class="form-control" />
                <span asp-validation-for="TiempoMinutos" class="text-danger"></span>
                <input asp-for="Estado" type="hidden" value="Activo" />
            </div>
        <br />
        <div class="mb-3 row">
            <div class="text-center">
                <input type="submit" value="Crear Servicio" class="btn btn-lg fondoVino text-light">
            </div>
        </div>
    </form>
    <br>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
 //Confirmar guardar
        function guardarRol() {
            Swal.fire({
                title: '¿Quieres crear el rol?',
                showCancelButton: true,
                confirmButtonText: 'Si',
                cancelButtonText: "No"
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Creando Rol...',
                        timer: 2000,
                        timerProgressBar: true,
                        showConfirmButton: false,
                        icon: "success"
                    }).then(() => {
                    document.getElementById("formularioCrearRol").submit();//subir formulario
                    });
                } else if (result.isDenied) {
                    Swal.fire('No se creó el rol', '', 'info');
                }
            });
        }
</script>

<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

AlexaSoft_ASP.NET/Views/Servicios/Delete.cshtml
@model AlexaSoft_ASP.NET.Models.Servicio

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Servicio</h1>

<h3>Deseas eliminar este Servicio?</h3>
<div class="container bordeVino px-4">
    <h4>Servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoMinutos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiempoMinutos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdServicio" />
        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

AlexaSoft_ASP.NET/Views/Servicios/Details.cshtml
@model AlexaSoft_ASP.NET.Models.Servicio

@{
    ViewData["Title"] = "Details";
}
<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Detalles Servicios</h1>
        </div>
        <div class="col-3">
        </div>
    </div>
</div>
<hr />

<div class="container bordeVino px-4">
    <h4>Servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoMinutos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiempoMinutos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>

<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

AlexaSoft_ASP.NET/Views/Servicios/Edit.cshtml
@model AlexaSoft_ASP.NET.Models.Servicio

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row">
        <div class="col-3">
            <div onclick="volver()" class="text-center">
                <i class="fa fa-angle-left fa-3x clickeable"></i>
            </div>
        </div>
        <div class="col-6">
            <h1 class="text-center">Editar Sericio</h1>
        </div>
        <div class="col-3">
        </div>
    </div> <!--Fin Row-->
</div>
<br>
<br>
<div class="container bordeVino px-4">
    <br>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdServicio" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoMinutos" class="control-label"></label>
                <input asp-for="TiempoMinutos" class="form-control" />
                <span asp-validation-for="TiempoMinutos" class="text-danger"></span>
                <input asp-for="Estado" type="hidden" value="Activo" />
            </div>
        <br />
        <div class="mb-3 row">
            <div class="text-center">
                <input type="submit" value="Editar" class="btn btn-lg fondoVino text-light">
            </div>
        </div>
    </form>
    <br>
</div>

<script>
    //Funcion Volver
    function volver() {
        window.history.back();
    }
</script>

<script>
   //Confirmar guardar
    function guardarRol() {
        Swal.fire({
            title: '¿Quieres modificar el rol?',
            showCancelButton: true,
            confirmButtonText: 'Si',
            cancelButtonText: "No"
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire({
                    title: 'Guardando datos...',
                    timer: 2000,
                    timerProgressBar: true,
                    showConfirmButton: false,
                    icon: "success"
                }).then(() => {
                    document.getElementById("formularioCrearRol").submit();//subir formulario
                });
            } else if (result.isDenied) {
                Swal.fire('No se guardaron los datos nuevos', '', 'info');
            }
        });
    }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlexaSoft_ASP.NET/Views/Servicios/Index.cshtml
@model IEnumerable<AlexaSoft_ASP.NET.Models.Servicio>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <h1 class="text-center">Servicios</h1>
        </div>
        <div class="col-3"></div>
    </div>
</div>

<p>
    <a asp-action="Create" class="btn btn-lg fondoVino text-light">Crear Servicio</a>
</p>
<table class="table fs-6 table-bordered table-responsive" style="overflow:auto;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoMinutos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TiempoMinutos)
            </td>
                <td class="text-center px-3">
                    <p class="m-0">
                        Estado:
                        <div class="form-check form-switch d-inline-block">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" @(item.Estado == "Activo" ? "checked" : "") onchange="cambiarEstado('@item.IdServicio')">
                        </div>
                    </p>
                </td>
            <td>
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.IdServicio">Editar</a>
                    <a class="btn btn-success" asp-action="Details" asp-route-id="@item.IdServicio">Detalle</a>
                    <a class="btn btn-danger delete-btn" asp-action="Delete" asp-route-id="@item.IdServicio">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</tableid>

<script>
    function cambiarEstado(idRol) {
        $.ajax({
            url: '@Url.Action("CambiarEstado", "Servicios")',
            type: 'POST',
            data: { idservicio: idRol },
            success: function (data) {
            },
            error: function (xhr, status, error) {
            }
        });
    }
</script>